spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:daybook}
spring.datasource.username=${DB_USER:daybook}
spring.datasource.password=${DB_PASSWORD:daybook}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false